# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 716)
        MainWindow.setStyleSheet("border-image: url(:/Anh giao dien dang nhap/Anh nen giao dien dang nhap.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_tennguoidung = QtWidgets.QLineEdit(self.centralwidget)
        self.login_tennguoidung.setGeometry(QtCore.QRect(150, 620, 211, 16))
        self.login_tennguoidung.setStyleSheet("border-image: url(:/Anh giao dien dang nhap/Mau trang.jpg);")
        self.login_tennguoidung.setObjectName("login_tennguoidung")
        self.login_matkhau = QtWidgets.QLineEdit(self.centralwidget)
        self.login_matkhau.setGeometry(QtCore.QRect(150, 640, 211, 16))
        self.login_matkhau.setStyleSheet("border-image: url(:/Anh giao dien dang nhap/Mau trang.jpg);")
        self.login_matkhau.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_matkhau.setObjectName("login_matkhau")
        self.login_dangky = QtWidgets.QPushButton(self.centralwidget)
        self.login_dangky.setGeometry(QtCore.QRect(250, 670, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.login_dangky.setFont(font)
        self.login_dangky.setStyleSheet("border-image: url(:/Anh giao dien dang nhap/Mau trang.jpg);")
        self.login_dangky.setObjectName("login_dangky")
        self.login_dangnhap = QtWidgets.QPushButton(self.centralwidget)
        self.login_dangnhap.setGeometry(QtCore.QRect(380, 630, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.login_dangnhap.setFont(font)
        self.login_dangnhap.setStyleSheet("border-image: url(:/Anh giao dien dang nhap/Mau trang.jpg);")
        self.login_dangnhap.setObjectName("login_dangnhap")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_tennguoidung.setPlaceholderText(_translate("MainWindow", "Nhập tên người dùng"))
        self.login_matkhau.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.login_dangky.setText(_translate("MainWindow", "Đăng ký ngay"))
        self.login_dangnhap.setText(_translate("MainWindow", "Đăng nhập"))
import Anh_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
