# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 714)
        MainWindow.setStyleSheet("border-image: url(:/Anh giao dien dang ky/Anh nen giao dien dang ky.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.reg_tennguoidung = QtWidgets.QLineEdit(self.centralwidget)
        self.reg_tennguoidung.setGeometry(QtCore.QRect(170, 630, 171, 16))
        self.reg_tennguoidung.setStyleSheet("border-image: url(:/Anh giao dien dang ky/Mau trang.jpg);")
        self.reg_tennguoidung.setObjectName("reg_tennguoidung")
        self.dangky_matkhau = QtWidgets.QLineEdit(self.centralwidget)
        self.dangky_matkhau.setGeometry(QtCore.QRect(170, 650, 171, 16))
        self.dangky_matkhau.setStyleSheet("border-image: url(:/Anh giao dien dang ky/Mau trang.jpg);")
        self.dangky_matkhau.setObjectName("dangky_matkhau")
        self.reg_dangky = QtWidgets.QPushButton(self.centralwidget)
        self.reg_dangky.setGeometry(QtCore.QRect(360, 640, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reg_dangky.setFont(font)
        self.reg_dangky.setStyleSheet("border-image: url(:/Anh giao dien dang ky/Mau trang.jpg);")
        self.reg_dangky.setObjectName("reg_dangky")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reg_tennguoidung.setPlaceholderText(_translate("MainWindow", "Nhập tên người dùng"))
        self.dangky_matkhau.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.reg_dangky.setText(_translate("MainWindow", "Đăng ký"))
import Anhdangky_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
